name: CI Workflow

on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        #The environment to execute the job
        runs-on: ubuntu-latest
        
        #Initialize the steps to run the tasks
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install fuzzywuzzy
                pip install pandas
                pip install playwright
                playwright install

            - name: Run tests
              run: python test_scrapping.py
